language: go

notifications:
  email:
    recipients:
      - ask@artprima.cz # Current maintainer
    on_success: change
    on_failure: always

go: 
 - "1.13"
 - "1.14"

before_script:
  - sudo sysctl -w vm.max_map_count=262144
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.23.7

script:
  - golangci-lint run       # run a bunch of code checkers/linters in parallel
  - go test -race ./... -v
  - go run examples/decoding/main.go
  - go run examples/encoding/main.go
